version: '3.8'

services:
  # Authentication Service
  auth-service:
    build: ./authentication
    image: ilhamelhamdi/aaw-auth-service:latest
    ports:
      - "8001:8000"
    env_file: .env
    environment:
      - DB_HOST=db-auth
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=auth
    depends_on:
      db-auth:
        condition: service_healthy
    command: ["./wait-for-it.sh", "db-auth:5432", "--", "./entrypoint.sh"]

  db-auth:
    image: postgres:latest
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9001:5432"
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Product Service
  product-service:
    build: ./product
    image: ilhamelhamdi/aaw-product-service:latest
    ports:
      - "8002:8000"
    env_file: .env
    environment:
      - DB_HOST=db-product
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=product
      - AUTH_MS_URL=http://auth-service:8000
      - TENANT_MS_URL=http://tenant-service:8000
    depends_on:
      db-product:
        condition: service_healthy
    command: ["./wait-for-it.sh", "db-product:5432", "--", "./entrypoint.sh"]

  db-product:
    image: postgres:latest
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9003:5432"
    volumes:
      - postgres_data_product:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d product"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Tenant Service
  tenant-service:
    build: ./tenant
    image: ilhamelhamdi/aaw-tenant-service:latest
    ports:
      - "8003:8000"
    env_file: .env
    environment:
      - DB_HOST=db-tenant
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tenant
      - AUTH_MS_URL=http://auth-service:8000
    depends_on:
      db-tenant:
        condition: service_healthy
    command: ["./wait-for-it.sh", "db-tenant:5432", "--", "./entrypoint.sh"]

  db-tenant:
    image: postgres:latest
    environment:
      POSTGRES_DB: tenant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9004:5432"
    volumes:
      - postgres_data_tenant:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tenant"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Orders Service
  orders-service:
    build: ./orders
    image: ilhamelhamdi/aaw-orders-service:latest
    ports:
      - "8004:8000"
    env_file: .env
    environment:
      - DB_HOST=db-orders
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=orders
      - PRODUCT_MS_URL=http://product-service:8000
    depends_on:
      db-orders:
        condition: service_healthy
    command: ["./wait-for-it.sh", "db-orders:5432", "--", "./entrypoint.sh"]

  db-orders:
    image: postgres:latest
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9002:5432"
    volumes:
      - postgres_data_orders:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 5s
      timeout: 5s
      retries: 10


  # Wishlist Service
  wishlist-service:
    build: ./wishlist
    image: ilhamelhamdi/aaw-wishlist-service:latest
    ports:
      - "8005:8000"
    env_file: .env
    environment:
      - DB_HOST=db-wishlist
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=wishlist
    depends_on:
      db-wishlist:
        condition: service_healthy
    command: ["./wait-for-it.sh", "db-wishlist:5432", "--", "./entrypoint.sh"]

  db-wishlist:
    image: postgres:latest
    environment:
      POSTGRES_DB: wishlist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9005:5432"
    volumes:
      - postgres_data_wishlist:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d wishlist"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data_auth:
  postgres_data_orders:
  postgres_data_product:
  postgres_data_tenant:
  postgres_data_wishlist: