apiVersion: v1
kind: Secret
metadata:
  name: orders-secret
type: Opaque
data:
  DB_USER: YWRtaW4=       # base64 of "admin"
  DB_PASSWORD: c2VjcmV0   # base64 of "secret"
  JWT_SECRET: YWF3X21hcmtldHBsYWNlX2p3dF9zZWNyZXQ= # base64 of "aaw_marketplace_jwt_secret"
  ADMIN_JWT_SECRET: YWRtaW5fYWF3X21hcmtldHBsYWNlX2p3dF9zZWNyZXQ= # base64 of "admin_aaw_marketplace_jwt_secret"